Add more extension files to be check
Files to be check only takes `ts` or `tsx` files but `js` and `jsx` files are sent back to the command so the error `error TS5042: Option 'project' cannot be mixed with source files on a command line.`  was thrown due to these files.